# Generated by Django 5.0.6 on 2024-07-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
