# Generated by Django 5.0.6 on 2024-06-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_guest_roomtype_booking_payment_room_booking_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
