# Generated by Django 5.0.6 on 2024-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_firstname_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
